### ISSUE TITLE
Documentation & cookbook

### ISSUE THREAD

**Issue by vifeng** [pimoroni/flotilla#3]
Hi, 
I just purchased the megachest from someone and found out that it's deprecated. 
1. could you still provide us with the cookbook, tutorials, some pdf ? 
2. Could you tell us a quick status of the project and if it can still run under Jessie and such.. ?
3. Is there a way to take advantage of the materials anyway if it doesn't work ? it would be a shame not to be able to use the sensors in some other ways...
4. Maybe you could provide with the website code of learn.flotil.la ?
Thank you a lot for your help

**Comment by Gadgetoid** [comment]
Before I close this issue and Archive this repository, I think I owe you a (albeit late) reply: 

1. I don't think we ever really had all that much, but the Python library has documentation - https://github.com/pimoroni/flotilla-python/tree/master/documentation
2. Completely EOL I'm afraid, albeit the Python code should still work
3. The Python library is probably the easiest way to do something with it https://github.com/pimoroni/flotilla-python - Rockpool probably has not aged well!
4. The web UI, if you're feeling brave, lives here: https://github.com/pimoroni/flotilla-rockpool and there was an offline installer that *might* still work for the Pi here: https://github.com/pimoroni/flotilla-offline
